### ISSUE TITLE
View doesn't change when using "LaTeX"

### ISSUE THREAD

**Issue by DashingDave** [colinc86/LaTeXSwiftUI#22]
I'm not sure of the proper terminology (it's either the View or the State not updating, something like that), but here's a simple example of what doesn't appear to be working properly (this was also occurring for version 1.2.3).

The following correctly changes the View when the Button is pressed:

`struct ContentView: View {
    @State var eqToggle: Bool = false
    
    var body: some View {
        VStack {
            Button("Toggle", action: {
                eqToggle.toggle()
            })
            Text("")
            eqToggle ? Text("$ 2x + \\sqrt{x} = 3 $ is the primary equation") : Text("The primary equation, $ -x^{2} + y_{0} > 12 \\text{,} $ is unknown.")
        }
    }
}
`

The following does not:

`
struct ContentView: View {
    @State var eqToggle: Bool = false    // 1st LaTeX call remains in place (true) or 2nd LaTeX call remains in place (false)
    
    var body: some View {
        VStack {
            Button("Toggle", action: {
                eqToggle.toggle()
            })
            Text("")
            eqToggle ? LaTeX("$ 2x + \\sqrt{x} = 3 $ is the primary equation") : LaTeX("The primary equation, $ -x^{2} + y_{0} > 12 \\text{,} $ is unknown.")
        }
    }
}
`

What's preventing the view from updating?

**Comment by rrpuente** [comment]
Hi, did you solve our issue?
It is happening also to me. 
I used a Text on top, just to test, the Text changes but the view LaTeX does not.

**Comment by grdleo** [comment]
I got the same issue. It seems the `LaTeX` does not support binding with the input. This makes the package unusable imo.

**Comment by grdleo** [comment]
@rrpuente @DashingDave 
I have a quick fix for this issue. Feel free to look at my PR #25.

**Comment by colinc86** [comment]
Fixed with v1.3.1
