### ISSUE TITLE
LaTeX view not updating when string input updated

### ISSUE THREAD

**Issue by grdleo** [colinc86/LaTeXSwiftUI#24]
Title is self explanatory. Take this code for example:

```Swift
import SwiftUI
import LaTeXSwiftUI

struct TestView: View {
    @State var varLatex = "$a$"
    
    var body: some View {
        VStack {
            Text(varLatex)
            LaTeX(varLatex)
            Button("Switch") {
                varLatex = "$b$"
            }
        }
    }
}

#Preview {
    TestView()
}
```

When the button is clicked, `varLatex` is updated and so is the `Text` view. But the `LaTeX` view is not updated... I have tried on multiple examples: whenever the input is updated, the view does not. And there is no workaround...

It feels like the `LaTeX` only works with constant strings, since iterating with `ForEach` over a constant list of strings works perfectly.

My knowledge in Swift is too little for me to open a PR... I hope this can be fixed soon!

**Comment by Alkenso** [comment]
have some issue. Fix is highly demanded and appreciated

**Comment by lcs-rgordon** [comment]
Same experience here. 

However, @colinc86 I've figured out that this problem was introduced at some point after version 1.1.0 based on my having created a project in early June 2023 that used LaTeXSwiftUI, and having everything work as expected.

For example, the code below works with version 1.1.0:

```swift
import SwiftUI
import LaTeXSwiftUI

struct ContentView: View {
    
    @State var radius = 0.0
    
    var body: some View {
        VStack {
            Text("\(radius)")
            Slider(value: $radius, in: 0...100)
            LaTeX("$$A=\\pi ^2$$")
            LaTeX("$$A=\\pi (\(radius))^2$$")
        }
        .padding()
    }
}
```

With the latest version, 1.3.0, when you drag the slider, the view is not updated.

I hope this helps. Thank-you for developing this package – it's really useful for myself as a Computer Science and Mathematics teacher, and, for my students.

**Comment by lcs-rgordon** [comment]
Follow-up: it is version 1.2.3 where the code in my comment above breaks. Any version lower than that and the LaTeX view updates as expected.

**Comment by colinc86** [comment]
The past few months have been very busy for me, so I apologize for not keeping up with this as much as I would have liked. I've updated the package to version 1.3.1, and it should work now with the examples you all have provided (which I very much appreciate). Thank you for the feedback!

**Comment by lcs-rgordon** [comment]
Completely understand about being busy – no need to apologize. Can confirm on my end as well that 1.3.1 works as expected, trying out the example I provided earlier. My students and I very much appreciate your efforts to build and maintain this package. Thanks!

**Comment by grdleo** [comment]
No need to apologise indeed, thank you for this great package!

**Comment by lcs-rgordon** [comment]
Hi @colinc86... it seems that this problem has re-surfaced as of, I think, version 1.4.0.

Trying the same example code I cited above, everything works great up to 1.3.2.

I can't actually test 1.4.0, as I received some package dependency errors when trying to add that version to a project just now:

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/d9d4ada6-bc93-4a44-8c4e-17f77d5ecf72" />
<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/875b9dfc-5401-4af3-a1bb-81a2eb4c79c8" />

Version 1.4.1 and 1.5.0 do not update the view when the bound value changes via the slider:

https://github.com/user-attachments/assets/12ec8896-894c-4fa2-a56f-abd1620fdf89

Thanks in advance for looking into this, when you have the time.

For now I'll ask my students to stick with version 1.3.2 – just wanted you to be aware that this issue has come up again.
